version: "3.8"
services:
    apigateway-interceptor:
        image: quay.io/rocats/apigateway-interceptor:latest
        container_name: apigateway-interceptor
        build:
            context: .
            args:
                PYTHON_VERSION: 3.12
        ports:
            - 5000:5000
        environment:
            WHITELIST_CHANNELS: ENC[AES256_GCM,data:W0rBvGBN3BRm9g==,iv:Ud7ZX02b/t8U3uyhpXR2c9zSJbkiGCoGwxfWdqSvABk=,tag:N93ot50OlfZNaeDfW+Wt6Q==,type:str]
            RELAY_SERVICE_ENDPOINT: ENC[AES256_GCM,data:WPZzJICYsgHIs5lFPHTA++MlWh1fcKP+AhjT8FBVCTklVoA48Q==,iv:pxg4kmjrSgqi8g6gJBdsKLB4+4B7OQal/v+he7uBumE=,tag:dIcscZ3CnltrSxsLt68xxg==,type:str]
        restart: unless-stopped
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zqdtv47nfckekj4ppvyapu6j8tmwun8ykf4agljdw2tsraa84slqq87xhf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRVBJSnpPd3VCek13bXY3
            YVlrS1lRWlU0QjkrQVNlQWVFbXRjQm5zUkZZClhjOTRDaHJYR01zWEFIY0VGOTFs
            OWllclhPV1hMN1dFNkxxbERyVnNKTDgKLS0tIG9BNnVDVW1FM1JtTngxKzZMeGxX
            WGRaNVRhd2NJMUNUK1FrSGUraHZ1Rm8KBuX2sdoNRRm9i+4Fpc0X2bkOaGOvsu4+
            6kwDPR6tcqj8pfKHRP5j3toS4cWgW6OlTx3mu28qA6NuWW5kuFPscw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-16T05:33:03Z"
    mac: ENC[AES256_GCM,data:ztLrlkIphxUYd9i/L9GGbl+nQoB5ZlS8pgRSQmq/XDXn0MbZ5/A4Wq0pzNzqfq2quOw2OYsp2SiHteXZF4DPgbKZfF8Fs9M1ehb30G8eoCKmd/Y81Y8/2z9y2QYIPJ83LNFnA2RmIcswf7637aQT/VT9QWlpxdADn/KzWHbre/U=,iv:dtlfIsi3tEBo27+6hZQdgKPhEdAW7KejBsUkp9MKFcI=,tag:69G/yemjqP6k3Su6NIDogA==,type:str]
    pgp:
        - created_at: "2023-12-16T05:33:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzVskl6rsqh0AQ/9GtCw9G++81tQyZuZiLLsASac/dn7VXO5NINWlS25u4ZF
            SJuPtJoEfeSJM3BtQ5ZWMasS4DIUhoNT3x9hdNHcFN3JXLN7pPdq+08+b0sGf5VM
            dIhJL0JPkZ/9qBsxdCThr+HMW2DoNFAOqas0Ep7LMM+Spt8BNUN4G28IPzTJyZCh
            jhYpA2mndq6dYZGddSPxwULKSmXGX1bjT/7KA9chCRUOZDDQnmudGMICLUSMuej3
            Qmdvv7OrIJNjDh+W3mkd2EuL9keT/zxe1jbZuo8AY9Mu6lTcScR1Y7k5HrPxuK1b
            emPxrzbozmcFeWYPJkEsTJDvpAJeQ/pl8j4y/C7wBbryq1xniIPVw0VHG4p+7Bd8
            eg3vHsJSgoWOczhoSnxFmbPbudXVuFIO8qFizGkQ29NFmHTukVKewTg7bpWCM7Ya
            V5MKOq8zWa11INFaJKIhHdpeXL7q2hFyF/Y7+U8Me/7ETds6zYhIxps4ZIlPDp4Y
            cnOBH/zBf+QTQsYNczdvf/3f/hE6OFZyJj/Dhgv2TGXGx4JyenjddBXla7JR2di7
            zFVhfmDHYhVgrgpXWGj8H00HG1Uv6s7Cx9zwE6H36B1Dmf0uvMKsNVXvH1tqTS9y
            zBoh108kxCLOW0FxEQb47gRaeBpYcHl1joUaxeoIrjWczoUjzw+wyUumVbIqjjXS
            XAEq95IzUT5qBN3Z2nI8kYu2vXnzKff6tYpnBQPqULLSypHcYjjlkqFph5BHJHyw
            PyaxN5sJKofV8UkzGHI9yt9z+rexzEnLgd0gK9j7LXdv4E28em8reLHEVmNo
            =YAgy
            -----END PGP MESSAGE-----
          fp: B08FE2644F9FC450AF425FF5B94F394B72884017
    encrypted_regex: ^(environment)$
    version: 3.8.1
