#                            _
#                      _       
#  _ __ ___   ___ __ _| |_ ___ 
# | '__/ _ \ / __/ _` | __/ __|
# | | | (_) | (_| (_| | |_\__ \
# |_|  \___/ \___\__,_|\__|___/
#
# https://github.com/rocats/apigateway-interceptor
#
#  Copyright (C) 2023 @rocats
#
#  This is a self-hosted software, liscensed under the Apache License. 
#  See /License for more information.

name: Build OCI Container (Prod)
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      dockerfile: Dockerfile
      image_name: rocats/${{ github.event.repository.name }}
      image_tag: prod-${{ needs.pre-actions.outputs.git_sha_short }}-${{ github.run_number }}
    outputs:
      image_tag: ${{ env.image_tag }}
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build - quay.io
        id: quay_build
        uses: aevea/action-kaniko@master
        with:
          registry: quay.io
          username: rocats
          password: ${{ secrets.QUAY_PASS }}
          image: ${{ env.image_name }}
          build_file: ${{ env.dockerfile }}
          tag: ${{ env.image_tag }}
          tag_with_latest: true
          cache: true
          cache_registry: quay.io/rocats/cache
          extra_args: --build-arg PYTHON_VERSION=3.10

      - name: Echo image uri
        run: |
          echo "ImageURI (quay.io): quay.io/${{ env.image_name }}:${{ env.image_tag }}"
